### ISSUE TITLE
您好，Is there a plan to released the whole source?

### ISSUE THREAD

**Issue by fireAj** [JianliWei1995/Monocular-Object-Height-Estimation#1]

**Comment by JianliWei1995** [comment]
Source code has been released, thanks for your interest!

**Comment by fireAj** [comment]
好的，谢谢老师




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JianliWei1995/Monocular-Object-Height-Estimation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月8日(星期二) 凌晨1:56
***@***.***&gt;;
抄送:&nbsp;"小 灰 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [JianliWei1995/Monocular-Object-Height-Estimation] 您好，Is there a plan to released the whole source? (Issue #1)





 
Closed #1 as completed.
