### ISSUE TITLE
YOLOv5模型的预训练权重文件无法下载

### ISSUE THREAD

**Issue by fireAj** [JianliWei1995/Monocular-Object-Height-Estimation#2]
老师，您好！在下载YOLOv5模型的预训练权重文件时跳转至登录页面，如下：

![capture_20230808091824239](https://github.com/JianliWei1995/Monocular-Object-Height-Estimation/assets/124151357/93f56408-b80b-4414-b459-98313ab9f772)

**Comment by JianliWei1995** [comment]
I updated the given link. You should have its access now.
