### ISSUE TITLE
point clouds

### ISSUE THREAD

**Issue by fireAj** [JianliWei1995/Monocular-Object-Height-Estimation#4]
是否支持点云数据？

**Comment by JianliWei1995** [comment]
We utilized YOLOv5 object detector for detecting image objects. You may replace this with object detector based on point cloud such as 3D point cloud object detection algorithm.

**Comment by fireAj** [comment]
Thanks，我们将使用PointNet替代YOLOv5目标检测器来检测图像对象

**Comment by JianliWei1995** [comment]
Sounds great, hopefully this paper and code would help
